### ISSUE TITLE
Error finding ModelSEEDDatabase variable

### ISSUE THREAD

**Issue by thh32** [linsalrob/PyFBA#5]
I have followed the instructions in creating the ModelSEEDDatabase variable as shown below;

thomas@Kiwi:~/PyFBA$ echo $ModelSEEDDatabase
/home/thomas/PyFBA/ModelSEEDDatabase

However when I test the setup.py code the following occurs;

thomas@Kiwi:~/PyFBA$ python setup.py test
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import PyFBA
  File "/home/thomas/PyFBA/PyFBA/__init__.py", line 5, in <module>
    import PyFBA.gapfill
  File "/home/thomas/PyFBA/PyFBA/gapfill/__init__.py", line 13, in <module>
    from .ecnumbers import suggest_reactions_using_ec
  File "/home/thomas/PyFBA/PyFBA/gapfill/ecnumbers.py", line 5, in <module>
    MODELSEED_DIR = os.environ['ModelSEEDDatabase']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'ModelSEEDDatabase'

Any idea how to solve this?

**Comment by cvagg** [comment]
I am having the same issue, did you solve it?

**Comment by travessny** [comment]
I am getting the same error. I swear I have tried everything.

**Comment by travessny** [comment]
I have the exact same issue. Could this be related to https://github.com/linsalrob/PyFBA/issues/4 or is it something else?

**Comment by travessny** [comment]
Found a solution. I no longer get this error when I export the variable as root user.

export ModelSEEDDatabase=/home/brian/ModelSEEDDatabase

**Comment by travessny** [comment]
Found a solution. I no longer get this error if I export the variable as root user. 
su - 
export ModelSEEDDatabase=/home/user1/ModelSEEDDatabase
